#############################################################################
# Makefile for building: p5
# Generated by qmake (2.01a) (Qt 4.2.3) on: Mon Mar 19 23:52:16 2007
# Project:  p5.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile p5.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
LEX           = flex
YACC          = yacc
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W  $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W  $(DEFINES)
LEXFLAGS      = 
YACCFLAGS     = -d
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include/QtOpenGL -I/usr/include -I/usr/X11R6/include -Itmp/moc -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/X11R6/lib -lGLU -lGL -lQtOpenGL -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = tmp/obj/

####### Files

SOURCES       = Canvas.cpp \
		Main.cpp \
		raytrace.cpp \
		vec3.cpp \
		fileio.cpp tmp/moc/moc_Canvas.cpp \
		tmp/moc/moc_control.cpp
OBJECTS       = tmp/obj/Canvas.o \
		tmp/obj/Main.o \
		tmp/obj/raytrace.o \
		tmp/obj/vec3.o \
		tmp/obj/fileio.o \
		tmp/obj/moc_Canvas.o \
		tmp/obj/moc_control.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/g++-multilib.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		p5.pro
QMAKE_TARGET  = p5
DESTDIR       = 
TARGET        = p5

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_control.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: p5.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf
	$(QMAKE) -unix -o Makefile p5.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile p5.pro

dist: 
	@$(CHK_DIR_EXISTS) tmp/obj/p51.0.0 || $(MKDIR) tmp/obj/p51.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) tmp/obj/p51.0.0/ && $(COPY_FILE) --parents Canvas.h raytrace.h control.h vec3.h fileio.h tmp/obj/p51.0.0/ && $(COPY_FILE) --parents Canvas.cpp Main.cpp raytrace.cpp vec3.cpp fileio.cpp tmp/obj/p51.0.0/ && $(COPY_FILE) --parents control.ui tmp/obj/p51.0.0/ && (cd `dirname tmp/obj/p51.0.0` && $(TAR) p51.0.0.tar p51.0.0 && $(COMPRESS) p51.0.0.tar) && $(MOVE) `dirname tmp/obj/p51.0.0`/p51.0.0.tar.gz . && $(DEL_FILE) -r tmp/obj/p51.0.0


yaccclean:
lexclean:
clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


/usr/lib/qt4/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: tmp/moc/moc_Canvas.cpp tmp/moc/moc_control.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) tmp/moc/moc_Canvas.cpp tmp/moc/moc_control.cpp
tmp/moc/moc_Canvas.cpp: ui_control.h \
		raytrace.h \
		vec3.h \
		Canvas.h \
		/usr/lib/qt4/bin/moc
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) Canvas.h -o tmp/moc/moc_Canvas.cpp

tmp/moc/moc_control.cpp: ui_control.h \
		fileio.h \
		raytrace.h \
		vec3.h \
		Canvas.h \
		control.h \
		/usr/lib/qt4/bin/moc
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) control.h -o tmp/moc/moc_control.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_control.h
compiler_uic_clean:
	-$(DEL_FILE) ui_control.h
ui_control.h: control.ui
	/usr/lib/qt4/bin/uic control.ui -o ui_control.h

compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_image_collection_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

tmp/obj/Canvas.o: Canvas.cpp Canvas.h \
		ui_control.h \
		raytrace.h \
		vec3.h \
		control.h \
		fileio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/Canvas.o Canvas.cpp

tmp/obj/Main.o: Main.cpp Canvas.h \
		ui_control.h \
		raytrace.h \
		vec3.h \
		control.h \
		fileio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/Main.o Main.cpp

tmp/obj/raytrace.o: raytrace.cpp raytrace.h \
		vec3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/raytrace.o raytrace.cpp

tmp/obj/vec3.o: vec3.cpp vec3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/vec3.o vec3.cpp

tmp/obj/fileio.o: fileio.cpp fileio.h \
		raytrace.h \
		vec3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/fileio.o fileio.cpp

tmp/obj/moc_Canvas.o: tmp/moc/moc_Canvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_Canvas.o tmp/moc/moc_Canvas.cpp

tmp/obj/moc_control.o: tmp/moc/moc_control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_control.o tmp/moc/moc_control.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

